name: Android CI

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "master","dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.402+6'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - run: echo $ENCODED_KEYSTORE | base64 -di > app/keystore.jks
      env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
          
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: |
          ${{github.workspace}}/app/build/outputs/apk/release/*.apk
          
    - uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: |
          ${{github.workspace}}/app/build/outputs/apk/debug/*.apk
          
